# Generated by Django 4.2.6 on 2024-10-31 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="date_of_birth",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="emergency_contact",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="emergency_phone",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="phone_number",
        ),
        migrations.AddField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Administrator"),
                    ("patient", "Patient"),
                    ("caregiver", "Caregiver"),
                    ("family", "Family Member"),
                    ("friend", "Friend"),
                ],
                default="family",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(blank=True, max_length=15)),
                ("address", models.TextField(blank=True, null=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("emergency_contact", models.CharField(blank=True, max_length=100)),
                ("emergency_phone", models.CharField(blank=True, max_length=15)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
